import { OnboardingStep } from '../types/onboarding';

export const dashboardOnboardingSteps: OnboardingStep[] = [
  {
    id: 'welcome',
    title: 'Welcome to Your Personal Budget Dashboard! 👋',
    content: 'Let\'s take a quick tour to help you get started with managing your finances effectively.',
    target: '.dashboard-header',
    position: 'bottom',
  },
  {
    id: 'net-worth',
    title: 'Your Net Worth Overview',
    content: 'This card shows your total net worth - the sum of all your account balances. It gives you a quick snapshot of your overall financial health.',
    target: '.net-worth',
    position: 'bottom',
    offset: { x: 0, y: 10 },
  },
  {
    id: 'monthly-income',
    title: 'Monthly Income Tracking',
    content: 'Here you can see your total monthly income. This includes all sources of income from the last 30 days.',
    target: '.income',
    position: 'bottom',
    offset: { x: 0, y: 10 },
  },
  {
    id: 'monthly-expenses',
    title: 'Monthly Expenses Monitor',
    content: 'This card tracks your monthly expenses. Keep an eye on this to ensure you\'re staying within your budget.',
    target: '.expenses',
    position: 'bottom',
    offset: { x: 0, y: 10 },
  },
  {
    id: 'investments',
    title: 'Investment Tracking',
    content: 'Monitor your monthly investments here. Building wealth through investments is key to long-term financial success.',
    target: '.investments',
    position: 'bottom',
    offset: { x: 0, y: 10 },
  },
  {
    id: 'savings-rate',
    title: 'Savings Rate Analysis',
    content: 'Your savings rate shows what percentage of your income you\'re saving. A higher savings rate means better financial health!',
    target: '.savings-rate',
    position: 'bottom',
    offset: { x: 0, y: 10 },
  },
  {
    id: 'accounts-count',
    title: 'Active Accounts',
    content: 'This shows how many financial accounts you have connected. More accounts mean better tracking of your finances.',
    target: '.accounts-count',
    position: 'bottom',
    offset: { x: 0, y: 10 },
  },
  {
    id: 'account-balances-chart',
    title: 'Account Balances Visualization',
    content: 'This chart breaks down your account balances visually. You can see which accounts hold the most money at a glance.',
    target: '.charts-grid .chart-container:first-child',
    position: 'top',
    offset: { x: 0, y: -10 },
  },
  {
    id: 'monthly-trends-chart',
    title: 'Monthly Trends Analysis',
    content: 'This chart shows how your income, expenses, and investments trend over time. Use it to spot patterns and make informed decisions.',
    target: '.charts-grid .chart-container:last-child',
    position: 'top',
    offset: { x: 0, y: -10 },
  },
  {
    id: 'completion',
    title: 'You\'re All Set! 🎉',
    content: 'Great job completing the tour! You now know how to navigate your dashboard. Remember, you can restart this tour anytime from the help menu.',
    target: '.dashboard',
    position: 'top',
    offset: { x: 0, y: 100 },
  },
];